[versions]
assertj = "3.24.2"
gson = "2.10.1"
jackson = "2.14.2"
junit = "5.9.2"
mockito = "5.1.1"
moshi = "1.14.0"
wiremock = "2.35.0"
slf4j = "2.0.6"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
wiremock = { module = "com.github.tomakehurst:wiremock-jre8", version.ref = "wiremock" }

[bundles]
mockito = [
    "mockito-core",
    "mockito-junit",
]
moshi = [
    "moshi",
    "moshi-adapters",
]
jackson = [
    "jackson",
    "jackson-databind"
]

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:0.7.0"
versions = "com.github.ben-manes.versions:0.44.0"
